### ISSUE TITLE
[Bug]: Transaction Management and Persistence Consistency in inspectIssuePropose and generateIssueProfile Methods

### ISSUE THREAD

**Issue by birariro** [OmniOneID/did-issuer-server#13]
### What happened?

Hello,

I have questions about transaction management in the inspectIssuePropose and generateIssueProfile methods, specifically regarding JPA dirty checking and rollback behavior.

In the [inspectIssuePropose method](https://github.com/OmniOneID/did-issuer-server/blob/1d6af53c4b80e4a978be68195fc8db3034614525/source/did-issuer-server/src/main/java/org/omnione/did/issuer/v1/service/IssueServiceBase.java#L149), the VcOffer entity is retrieved from the JPA repository, and the setTransactionId method is used to set a new transactionId. 
```java
       if (vcOffer != null) {
              // FIXME: Offer에 횟수제한이 없으면 Transaction이 계속 생성되는 문제가 있음
              //  5회 제한
              vcOffer.setTransactionId(transaction.getId()); // <- here
          }
```

However, since there's no @Transactional annotation on this method, I believe JPA's dirty checking won't be triggered, meaning the update won’t be persisted. Could you clarify if there is an intended mechanism to persist this change, or was the absence of @Transactional intentional here?

Additionally, in the [generateIssueProfile method](https://github.com/OmniOneID/did-issuer-server/blob/1d6af53c4b80e4a978be68195fc8db3034614525/source/did-issuer-server/src/main/java/org/omnione/did/issuer/v1/service/IssueServiceBase.java#L215),

 since there is also no @Transactional annotation, I'm concerned about potential consistency issues if one of the save operations fails. For example, if vcProfileQueryRepository.save succeeds but e2EQueryRepository.save fails, will vcProfileQueryRepository roll back correctly, or could it result in partial data persistence? 

```java
            vcProfileQueryService.save(VcProfile.builder()
                    .profileId(profile.getId())
                    .transactionId(transaction.getId())
                    .did(holder.getDid())
                    .nonce(reqE2e.getNonce())
                    .userId(user.getId())
                    .build());

            log.debug("\t--> E2E save to DB");
            e2EQueryService.save(E2E.builder()
                    .curve(reqE2e.getCurve())
                    .cipher(reqE2e.getCipher())
                    .padding(reqE2e.getPadding())
                    .nonce(reqE2e.getNonce())
                    .sessionKey(encodedSessionKey)
                    .transactionId(transaction.getId())
                    .build());
```

Without a transaction, it seems difficult to ensure atomicity across these repository calls.
Could you clarify if there’s a specific strategy for handling these potential persistence and rollback concerns, or if the absence of @Transactional was by design?

Thank you for your insights!

### Version

V1.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yoongyu-lee** [comment]
Thank you for bringing this to my attention.

The absence of the @Transactional annotation in the inspectIssuePropose and generateIssueProfile methods was unintentional. To ensure JPA’s dirty checking and proper rollback mechanisms work as expected, we’ll be adding @Transactional. Additionally, I’ll be reviewing the entire codebase to identify any similar transaction management issues in other methods, ensuring transaction integrity across the project.

I’ll mark this issue as confirmed and begin the necessary updates.

Thank you for your thorough review and attention to detail!

**Comment by birariro** [comment]
hello @yoongyu-lee 

Would it be alright if I submit a PR to address transaction consistency improvements?

**Comment by yoongyu-lee** [comment]
@birariro 
Thank you for offering to help! Yes, please feel free to submit a PR to address transaction consistency improvements. Your contributions are very much appreciated.

**Comment by gw-nam** [comment]
hello @birariro 
Thank you for the PR #14 !
The merge is complete, so I'm closing this issue now.
